### ISSUE TITLE
Nvidia Support

### ISSUE THREAD

**Issue by tom-doerr** [djpohly/dwl#11]
Does dwl work with the proprietary Nvidia GPU driver?
Getting a Wayland window manager to work with Nvidia doesn't seem to be trivial (https://drewdevault.com/2017/10/26/Fuck-you-nvidia.html).
 I need CUDA support, so I can't switch to the free Nvidia driver.

**Comment by djpohly** [comment]
Given a [more recent explanation from the same wlroots developer](https://drewdevault.com/2019/02/10/Wayland-misconceptions-debunked.html#wayland-doesnt-support-nvidia), it seems that (1) the current answer is no, and (2) Nvidia doesn't consider support for the Linux graphics stack a priority, and (3) it's unlikely that wlroots (on which both swaywm and dwl are based) will be bending over backwards to do work that should be done in the graphics driver.

Since it would run counter to suckless principles to implement a graphics driver in dwl itself, I'm going to close the issue for this repo.  If you want to apply some pressure, consider which product you paid money for and use that leverage! :wink:
