### ISSUE TITLE
Nvidia support base on Weston

### ISSUE THREAD

**Issue by chpack** [djpohly/dwl#114]
Is that possible to modifie weston to work as simple as dwm?

From what I know, the reason why dwl don't suppor nvidia card is wlroots don't support nvidia's eglstream. And weston has a patch that let weston work on nvidia's eglstream. So, maybe we can use that code to implement a dwm?

**Comment by djpohly** [comment]
Thanks for the suggestion. dwl relies on the wlroots renderer to handle interactions with the video card, so that functionality wouldn't actually belong in this codebase.  The wlroots/sway devs give some good reasons [why EGLStreams is not a good solution for Wayland](https://github.com/swaywm/sway/issues/490#issuecomment-471745501).

There is a user who has made an effort to [port the EGLStreams patches to wlroots](https://github.com/danvd/wlroots-eglstreams) if you want to check that out, but it doesn't seem likely to become official.  Other than that, you can either use Nouveau, wield your leverage as a paying customer to pressure Nvidia to get their act together, or vote with your purchases and buy from a different manufacturer.

**Comment by djpohly** [comment]
Side note: you may want to keep watching for any news about [Nvidia and GBM](https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-GBM-Mesa-Backend-Alt), which could mean Nvidia is finally thinking about fixing the issue at the source.
