### ISSUE TITLE
You are out of SLOC

### ISSUE THREAD

**Issue by kanashimia** [djpohly/dwl#116]
Github says that dwl.c is 2276 SLOC, which is bigger than 2000.
(':

**Comment by djpohly** [comment]
Haha, well, I haven't been counting blank lines or comments, since I think it is a mistake to disincentivize readable, well-documented code.  (Acknowledged, this is different from dwm's approach.)  According to `cloc` it's still at 1932 lines of *code* code, and it may grow and shrink before we reach v1.0.

**Comment by Fuseteam** [comment]
oh interesting so github counts comments
