### ISSUE TITLE
How do I compile and install in FreeBSD

### ISSUE THREAD

**Issue by kimuxer** [djpohly/dwl#176]
How can I modify the file to get dwl compiled and installed on FreeBSD

**Comment by jbeich** [comment]
1. Switch to `/latest` package set (for wlroots >= 0.15.0) or wait until `/quarterly` is based on `2022Q1` branch (in ~2 weeks)
2. Install dependencies: `pkg install gmake pkgconf evdev-proto wayland-protocols wlroots`
3. Run `gmake` in dwl checkout directory
4. Launch `./dwl` (default config) on top of Xorg or another Wayland compositor
5. Confirm a new window appears (ignore benign errors like ` No free output buffer slot`)
6. Close the window
7. Edit `config.h` to change terminal emulator, key bindings, etc.
8. Run `gmake`
9. Copy or symlink `dwl` binary under `~/bin` or anywhere else under `PATH`
10. Enjoy

Disclaimer: I don't use dwl myself.

**Comment by jbeich** [comment]
I've packaged [dwl](https://www.freshports.org/x11-wm/dwl) since you're not the first FreeBSD user wanting to try it. Suggestions welcome. Like dwm building the package with custom config is done via `DWL_CONF` in make.conf(5) and extra patches dropped under `files/` subdirectory.

BTW, if you need help with Wayland in general use [x11@](https://lists.freebsd.org/subscription/freebsd-x11) mailing list. Official documentation isn't ready yet (see [WIP](https://reviews.freebsd.org/D32436)), so don't be ashamed to ask stupid questions.

**Comment by kimuxer** [comment]
I'm so stupid, I thought there was no dwl in ports
Thank u.I successfully entered the desktop.But I only see a full-screen gray desktop(this is not the point, I know it is because there is no wallpaper set)
My problem is that I can’t find Tags on the screen,I am not using XWayland.Do i need to install it？

**Comment by jbeich** [comment]
- downstream package didn't exist when this issue was opened but it was easier to create than explain (I did try but it was awkwardly long and confusing)
- dwl doesn't have a bar, so selected tags are displayed on console
- to set a wallpaper install `swaybg` package then run `daemon -f swaybg -i /path/to/image.png`
- Xwayland support (enabled by default in downstream package) seems broken (see https://github.com/djpohly/dwl/issues/177). Can be worked around by running in `cage` (another Wayland compositor) at the cost of copy-paste support.
