### ISSUE TITLE
system hang after mod+shift+q

### ISSUE THREAD

**Issue by guyuming76** [djpohly/dwl#224]
i start dwl from tty with dbus-run-session dwl -s foot

when i try to quit dwl with mod+shift+q, system just hang, i cannot even switch tty with ctrl+alt+F#.

after debugging with cgdb, i found that it is because of following code in run method:
```

	if (startup_cmd) {
		kill(startup_pid, SIGTERM);
		waitpid(startup_pid, NULL, 0);
	}
```

dwl is blocked at waitpid.

so, i wonder why there should be waitpid call here, what if just send the kill message and continue without waitpid?

if i close the foot VT with exit command and press mod+shift+q, dwl with exit to tty.

**Comment by djpohly** [comment]
Hm. This could be an interaction with recent changes to reaping. Is the foot process still running at this point? Ideally the program you use for your session manager should exit on receipt of SIGTERM.

**Comment by siemato** [comment]
foot has an optional urxvt-style deamon and new wayland clients connect to it as clients. Pure speculation, if that causes the issue though.

**Comment by dnkl** [comment]
I was pinged over at https://codeberg.org/dnkl/foot/issues/651#issuecomment-468120. I'm guessing a bit here, but it looks like dwl is keeping the Wayland socket open, but without actually serving it (obviously, since it's stuck in a `waitpid()`) .

As long as the Wayland socket is up, foot will exit "nicely"; it will unmap itself and call destroy/release on all the Wayland resources. This wont work if the compositor isn't serving the socket.

I would suggest simply closing the socket before going into the `waitpid()`.

**Comment by dnkl** [comment]
(btw, you can always ping me directly here on github)

**Comment by Sevz17** [comment]
Fixed in https://github.com/djpohly/dwl/commit/d26ddfc7fd36d420990eee94d3c4badb90217bd1
@dnkl, thanks for the hint!
