### ISSUE TITLE
dpms on/off

### ISSUE THREAD

**Issue by antoniocorbi** [djpohly/dwl#394]
Hi,

Is it possible to make this pattern work: on keypress I want to lock the screen (waylock, swaylock, etc...) but before I want to set dpms off and after typing passwd turn dpms on.
I've managed to make this work under Sway and Hyprland but I'm struggling to make it work under Dwl.

**Comment by josephreynolds1** [comment]
I am currently doing this by patching DWL with the output power management patch.
https://github.com/djpohly/dwl/wiki/outputPowerManagement

The patch doesn't apply 100% correct and I have to copy the wayland protocol xml it generates to the protocols folder and I believe edit the MakeFile as well.

Also have to run the patch command with these switches
patch --dry-run --ignore-whitespace --fuzz 3 -d dwl < output-power-management.patch

I am also using waylock and the dpms-off command so my config.h looks like this with a ctrl+alt+del to lock the screen

{ WLR_MODIFIER_CTRL|MODKEY,  XKB_KEY_Delete,     spawn,          SHCMD("waylock --init-color '#000000' --input-color '#005577' --fail-color '#CC3333' & sleep 0.5 && dpms-off") },

https://github.com/lilydjwg/dpms-off

Honestly I really feel like this patch (outputPowerManagement) and the Pointer Constraints patch really just need to be baked into DWL at this point for it to be really usable.

**Comment by sevz17** [comment]
I don't plan to implement [zwlr_output_power_manager_v1](https://wayland.app/protocols/wlr-output-power-management-unstable-v1), because [zwlr_output_manager_v1](https://wayland.app/protocols/wlr-output-management-unstable-v1) already is capable of turn on/off outputs. You can use `for o in $(wlr-randr | grep -e "^[^[:space:]]\+" | cut -d " " -f 1); do wlr-randr --output "${o}" --toggle; done` to toggle all outputs.

**Comment by antoniocorbi** [comment]
Thanks @sevz17 for your comment.

I know wlr-randr and, indeed, your tip works for me if I execute something like this from a terminal:

```
for o in $(wlr-randr | grep -e "^[^[:space:]]\+" | cut -d " " -f 1); do wlr-randr --output "${o}" --toggle; done;
read a; 
for o in $(wlr-randr | grep -e "^[^[:space:]]\+" | cut -d " " -f 1); do wlr-randr --output "${o}" --toggle; done
```

But if I write those lines into a script to be invoked (spawned) via key-combination, in turn, defined in config.h then it doens't work. Outputs get dpms-off by the first toggle but the input isn't _redirected_ to the 'read a' so the second toggle never gets executed.

I've used a `read`command in the middle but my original intention was to use `swaylock/waylock`, etc...

Do you know if there is a way to get this working?
Thanks for your work in Dwl!

**Comment by sevz17** [comment]
Well, this is my swayidle config:
```conf
timeout 600 "chayang -d 5 && for o in $(wlr-randr | grep -e '^[^[:space:]]\+' | cut -d ' ' -f 1); do wlr-randr --output \"\${o}\" --off; done" resume "for o in $(wlr-randr | grep -e '^[^[:space:]]\+' | cut -d ' ' -f 1); do wlr-randr --output \"\${o}\" --on; done"
timeout 900 "swaylock --daemonize --image $(chbg --print) --scaling fill"
idlehint 1140
before-sleep "swaylock --daemonize --image $(chbg --print) --scaling fill"
after-resume "for o in $(wlr-randr | grep -e '^[^[:space:]]\+' | cut -d ' ' -f 1); do wlr-randr --output \"\${o}\" --on; done"
lock "swaylock --daemonize --image $(chbg --print) --scaling fill"

```

**Comment by fauxmight** [comment]
@sevz17: With multiple monitors, I found I needed to change the first line of your swayidle config above to
```
timeout 600 "chayang -d 5 && for o in $(wlr-randr | grep -e '^[^[:space:]]\+' | cut -d ' ' -f 1 | tr '\n' ' '); do wlr-randr --output \"\${o}\" --off; done" resume "for o in $(wlr-randr | grep -e '^[^[:space:]]\+' | cut -d ' ' -f 1 | tr '\n' ' '); do wlr-randr --output \"\${o}\" --on; done"
```

Adding `| tr '\n' ' '` to the `wlr-randr --off` and `wlr-randr --on` calls was necessary because `sh -c` does not seem to handle the newline between outputs correctly (even though it does fine if you run this from `sh` in a terminal).

I add this in case another multi-monitor user runs into the same failure. This is a nice solution for monitor DPMS effect. Thanks.

**Comment by sevz17** [comment]
> Adding `| tr '\n' ' '` to the `wlr-randr --off` and `wlr-randr --on` calls was necessary because `sh -c` does not seem to handle the newline between outputs correctly (even though it does fine if you run this from `sh` in a terminal).
> 

I guess is a difference between bash and dash.

> @sevz17: With multiple monitors, I found I needed to change the first line of your swayidle config above to
> 
> ```
> timeout 600 "chayang -d 5 && for o in $(wlr-randr | grep -e '^[^[:space:]]\+' | cut -d ' ' -f 1 | tr '\n' ' '); do wlr-randr --output \"\${o}\" --off; done" resume "for o in $(wlr-randr | grep -e '^[^[:space:]]\+' | cut -d ' ' -f 1 | tr '\n' ' '); do wlr-randr --output \"\${o}\" --on; done"
> ```
> 

Actually I changed the command [time ago](https://gitlab.com/sevz17/dotfiles/-/commit/d5f865052e685c214aaddb14db5f6fb2ea2550d9), now it uses awk instead, about the line delimiter I updated it [just now](https://gitlab.com/sevz17/dotfiles/-/commit/75385677ffc62200d085d01418ae162a81bf67bc)

By the way, instead of piping the result to `tr`, you can add `-z` to `cut`, it will use NUL instead of newline

**Comment by dguibert** [comment]
> With multiple monitors, I found I needed to change the first line of your swayidle config above to

On a multiple monitors setup, I have my windows moving from the first monitor that is turned off to the monitor that is still on.

When the monitors go on again on resume, the windows are left on ths second monitor.

Is it possible to put all the montiors off at the same time? or restoring the window placement after resume?

**Comment by fauxmight** [comment]
@dguibert @fictitiousexistence : I don't think there is an easy fix on this one.
I've messed with the script quite a bit, but even calling 

`wlr-randr --output OUTPUT1 --off --output OUTPUT2 --off`

followed by

`wlr-randr --output OUTPUT1 --on --output OUTPUT2 --on`

still results in all windows pushed to OUTPUT2.

At present, I deal with this by manually moving the windows necessary back to where they "belong" after a sleep-resume cycle.

**Comment by fictitiousexistence** [comment]
@fauxmight ah poo :( 

During your testing did you run into any other issues? 

Did you run into the issue where windows disappear completely (I think they're just killed) when turning back on?
