### ISSUE TITLE
Typing freezes touchpad cursor movement

### ISSUE THREAD

**Issue by gitRaiku** [djpohly/dwl#406]
## Info
dwl version: 0.4
wlroots version:
```
$ doas pacman -Qs wlroots
local/wlroots 0.16.2-1
```
Libinput version
```
$ doas pacman -Qs libinput
local/libinput 1.22.1-1
```
## Description

You cannot move the cursor using a touchpad while simultaneously typing.

This does not happen while using a mouse or when using dwm in X11.

**Comment by gozenka** [comment]
Did you set this in config.h?
```
/* Trackpad */
...
static const int disable_while_typing = 0;
...
```

**Comment by gitRaiku** [comment]
Ah, sorry, i missed that option while searching for what could be causing this. Thank you!

Though this does raise the question. Why is it default behaviour to stop the trackpad while typing? I see it more so as a handicap than an actual improvement on most systems.

**Comment by fauxmight** [comment]
This is a common option (and a common choice for the option) with laptops. Laptops are the most common form factor possessing a trackpad and in this form factor, it is easy to accidentally move the cursor while typing (and thus accidentally move focus) and have keyboard input suddenly directed to the wrong client.

If the issue is resolved, please feel free to close it.

**Comment by gitRaiku** [comment]
Different people different preferences i guess. Thanks for the help.
