### ISSUE TITLE
Compilation issue (Ubuntu 22.04 LTS)

### ISSUE THREAD

**Issue by spndnqq** [djpohly/dwl#469]
**Getting error:**
dwl.c:27:10: fatal error: wlr/types/wlr_idle_notify_v1.h: No such file or directory
   27 | #include <wlr/types/wlr_idle_notify_v1.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:60: dwl.o] Error 1

**Installed Version:**
libwlroots-dev=0.15.1-2
wayland-protocols=1.25-1

![Screenshot from 2023-08-27 11-46-46](https://github.com/djpohly/dwl/assets/135336929/1fb9933c-93e6-46a6-a110-4cbc8a354703)

**Comment by sevz17** [comment]
See #341.

**Comment by spndnqq** [comment]
Thanks for reply @sevz17, but after switching to https://github.com/djpohly/dwl/commit/87d87cc4041a997d00ebf234ca5118b9248a3b95 I got these following errors.
![Screenshot from 2023-08-27 12-49-00](https://github.com/djpohly/dwl/assets/135336929/229080df-b46d-4346-83e6-7ce07817b1b0)

**Comment by fauxmight** [comment]
@spndnqq You are trying to use a `config.h` that you made from a recent commit's `config.def.h`. This won't work. There have been too many changes in `config.def.h`.

When you switch to 87d87cc, you will need to make a `config.h` from the `config.def.h` in 87d87cc.

**Comment by spndnqq** [comment]
@fauxmight Thank you very much.
`git checkout -b ubuntu 87d87cc` solved the issue.

**Comment by easbarba** [comment]
Same issue here, but ain't that commit quite old, what about more recent commits? Thanks for the help anyway :)

**Comment by fauxmight** [comment]
@easbarba "Same issue here"
There are two different problems discussed here, and the issue is already closed.


1) "but ain't that commit quite old, what about more recent commits"
If you are building dwl against wlroots version 0.15, then you will _need_ to use an old commit of dwl that builds against out-of-date wlroots 0.15

2) No matter what commit you are using, you will need to edit the `config.def.h` from that commit to make your own `config.h`
If you try to use a `config.def.h` that is significantly older or newer you will run into problems like the second one mentioned above in this issue.

If the steps discussed here don't address the trouble you are having, please open your own issue with some description of your trouble.

**Comment by easbarba** [comment]
Oh, indeed, thanks!
